export class Soundscape{
 constructor(){this.ctx=null;this.enabled=false;this.volume=.55;this.nextBird=5;this.nextChime=8;this.stepAt=0;this.tick=0;}
 async init(){if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;this.ctx=new AC();const c=this.ctx;this.master=c.createGain();this.master.gain.value=0;const comp=c.createDynamicsCompressor();comp.threshold.value=-18;comp.ratio.value=3;this.master.connect(comp);comp.connect(c.destination);const n=c.sampleRate*5;this.noise=c.createBuffer(1,n,c.sampleRate);let last=0;const data=this.noise.getChannelData(0);for(let i=0;i<n;i++){last=(last+.035*(Math.random()*2-1))/1.035;data[i]=last*3;}
 this.wind=this.layer('lowpass',900);this.sea=this.layer('lowpass',420);this.leaves=this.layer('highpass',1450);this.enabled=true;}
 await this.ctx.resume();this.setEnabled(true);return true;}
 layer(type,hz){const c=this.ctx,s=c.createBufferSource();s.buffer=this.noise;s.loop=true;const filter=c.createBiquadFilter();filter.type=type;filter.frequency.value=hz;const g=c.createGain();g.gain.value=0;const pan=c.createStereoPanner();s.connect(filter);filter.connect(g);g.connect(pan);pan.connect(this.master);s.start(Math.random()*.2);return{filter,g,pan};}
 setEnabled(on){this.enabled=on;if(this.ctx){this.master.gain.cancelScheduledValues(this.ctx.currentTime);this.master.gain.setTargetAtTime(on?this.volume*.6:0,this.ctx.currentTime,.25);}}
 setVolume(v){this.volume=v;this.setEnabled(this.enabled);}
 step(speed,park){if(!this.ctx||!this.enabled)return;const c=this.ctx,t=c.currentTime;if(t<this.stepAt)return;this.stepAt=t+Math.max(.32,.52-speed*.035);const s=c.createBufferSource();s.buffer=this.noise;const f=c.createBiquadFilter();f.type='bandpass';f.frequency.value=park?480:780;f.Q.value=.6;const g=c.createGain();g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.30,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+.13);s.connect(f);f.connect(g);g.connect(this.master);s.start(t,Math.random()*3);s.stop(t+.16);s.onended=()=>{s.disconnect();f.disconnect();g.disconnect();};}
 tone(freq,delay,duration,gain,pan=0,endFreq=null){const c=this.ctx,t=c.currentTime+delay,o=c.createOscillator(),g=c.createGain(),p=c.createStereoPanner();o.type='sine';o.frequency.setValueAtTime(freq,t);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,t+duration*.7);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+duration);p.pan.value=pan;o.connect(g);g.connect(p);p.connect(this.master);o.start(t);o.stop(t+duration+.03);o.onended=()=>{o.disconnect();g.disconnect();p.disconnect();};}
 update(t,gust,z,yaw,speed,park){if(!this.ctx||!this.enabled)return;if(speed>.35)this.step(speed,park);if(t<this.tick)return;this.tick=t+.12;const c=this.ctx,now=c.currentTime;this.wind.g.gain.setTargetAtTime(.11+gust*.15,now,.4);this.wind.filter.frequency.setTargetAtTime(380+gust*680,now,.5);this.wind.pan.pan.setTargetAtTime(Math.sin(yaw+.7)*.36,now,.8);const near=Math.max(0,Math.min(1,(20-z)/65));this.sea.g.gain.setTargetAtTime(near*(.17+.15*(.5+.5*Math.sin(t*.55))),now,.7);this.sea.pan.pan.setTargetAtTime(Math.sin(yaw)*near*.7,now,.5);this.leaves.g.gain.setTargetAtTime(gust*(park?.40:.17),now,.6);if(t>this.nextBird){const p=Math.sin(t*.31)*.8;this.tone(near>.7?1100:2400,0,.23,.033,p,near>.7?700:3300);this.tone(near>.7?1000:2900,.29,.19,.020,p,near>.7?770:2200);this.nextBird=t+9+Math.random()*13;}if(t>this.nextChime){if(z>12&&gust>.35){const notes=[1568,2093,2349];const pan=Math.sin(yaw-1.2)*.8;this.tone(notes[Math.floor(Math.random()*3)],0,1.7,.024,pan);this.tone(3136,.11,1,.006,pan);}this.nextChime=t+13+Math.random()*12;}}
 suspend(){this.ctx?.suspend();}resume(){if(this.enabled)this.ctx?.resume().catch(()=>{});}
}
