import * as T from './vendor/three.module.js';
import {buildWorld,createDog} from './world.js';
import {height,canWalk,constrainDog} from './routes.js';
import {Soundscape} from './audio.js';
const $=id=>document.getElementById(id),touch=matchMedia('(pointer:coarse)').matches;
const sideOffset=touch?.30:.65;
let started=false,paused=false,elapsed=0,last=0,windSetting=.55,bob=false,petUntil=0,toastUntil=0,lastPlace='',lastZoneTime=0,frameCount=0,frameTotal=0,quality='auto',resolvedQuality=false;
let yaw=0,pitch=-.17,joyX=0,joyY=0,lookId=null,joyId=null,lookX=0,lookY=0,walkPhase=0;
const keys=new Set(),player=new T.Vector3(0,height(0,16),16),velocity=new T.Vector3(),forward=new T.Vector3(),right=new T.Vector3(),goal=new T.Vector3(),v=new T.Vector3();
const sound=new Soundscape(),scene=new T.Scene();scene.background=new T.Color('#c0d6d1');scene.fog=new T.FogExp2('#c2d3c8',.0052);
const camera=new T.PerspectiveCamera(64,innerWidth/innerHeight,.08,800);camera.rotation.order='YXZ';
let renderer;try{renderer=new T.WebGLRenderer({antialias:!touch,powerPreference:'high-performance',alpha:false});}catch(e){$('error').style.display='grid';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,touch?1.35:1.75));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.22;$('view').append(renderer.domElement);
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();paused=true;sound.suspend();$('errorText').textContent='描画が中断されました。ほかのアプリを閉じて、もう一度開いてください。';$('error').style.display='grid';});
scene.add(new T.HemisphereLight('#ffe9bd','#91afa0',2.4));const sun=new T.DirectionalLight('#ffddb0',2.5);sun.position.set(-90,120,-90);scene.add(sun);
const sky=new T.Mesh(new T.SphereGeometry(650,24,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{},vertexShader:'varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 p;void main(){float h=normalize(p).y;vec3 low=vec3(.94,.83,.66),high=vec3(.43,.66,.74);vec3 col=mix(low,high,smoothstep(-.02,.75,h));vec3 sunDir=normalize(vec3(-.38,.30,-1.));float a=max(0.,dot(normalize(p),sunDir));col+=vec3(.12,.065,.018)*pow(a,25.);gl_FragColor=vec4(col,1.);}',toneMapped:false}));scene.add(sky);
const sunDisc=new T.Mesh(new T.SphereGeometry(6,20,12),new T.MeshBasicMaterial({color:'#fff0c1',fog:false}));sunDisc.position.set(-145,115,-380);scene.add(sunDisc);
// The ocean has low-frequency height changes and a fine, moving glint pattern.
const water=new T.Mesh(new T.PlaneGeometry(1100,680,76,56),new T.ShaderMaterial({uniforms:{time:{value:0},breeze:{value:.5}},vertexShader:'uniform float time;varying vec3 pos;void main(){vec3 p=position;p.z=sin(p.x*.035+time*.6)*.10+cos(p.y*.06+time*.7)*.07;pos=p;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}',fragmentShader:'uniform float time;uniform float breeze;varying vec3 pos;void main(){float a=sin(pos.x*.19+pos.y*.39+time*.9);float b=sin(pos.x*.50-pos.y*.24+time*1.2);float ripple=.5+.5*a*b;vec3 col=mix(vec3(.23,.49,.51),vec3(.48,.68,.65),ripple*.6);float glint=pow(max(0.,sin(pos.x*1.6+pos.y*.8+time*1.1)*cos(pos.y*1.9-time)),20.);col+=vec3(.9,.76,.43)*glint*(.17+breeze*.16);float far=smoothstep(60.,330.,pos.y);col=mix(col,vec3(.67,.76,.71),far);gl_FragColor=vec4(col,1.);}',side:T.DoubleSide}));water.rotation.x=-Math.PI/2;water.position.set(0,.05,-389);scene.add(water);
// Quiet islands soften the horizon.
const islandMat=new T.MeshLambertMaterial({color:'#7f9f92'});for(let i=0;i<8;i++){const island=new T.Mesh(new T.IcosahedronGeometry(1,2),islandMat);island.position.set(-340+i*100,-7,-240-(i%3)*58);island.scale.set(48+(i%3)*17,19+(i%4)*7,29);scene.add(island);}
const clouds=[];const cloudMat=new T.MeshBasicMaterial({color:'#f1e6ce',transparent:true,opacity:.35,depthWrite:false});for(let i=0;i<7;i++){const group=new T.Group();for(let j=0;j<3;j++){const puff=new T.Mesh(new T.IcosahedronGeometry(1,2),cloudMat);puff.position.set(j*13,Math.sin(j+i)*2,0);puff.scale.set(20,3.5,9);group.add(puff);}group.position.set(-250+i*85,72+(i%3)*15,-260-(i%2)*50);scene.add(group);clouds.push(group);}
const world=buildWorld(scene),dog=createDog();scene.add(dog.dog);dog.dog.position.set(sideOffset,height(sideOffset,13.2)+.07,13.2);
// A real curve joins the dog's collar to the walker's hand, with a soft slack.
const leashPos=new Float32Array(25*3),leashGeo=new T.BufferGeometry();leashGeo.setAttribute('position',new T.BufferAttribute(leashPos,3).setUsage(T.DynamicDrawUsage));const leash=new T.Line(leashGeo,new T.LineBasicMaterial({color:'#856f51'}));leash.frustumCulled=false;scene.add(leash);
const hand=new T.Vector3(),collar=new T.Vector3(),mid=new T.Vector3();
// Airborne leaves are tiny world-space objects: the same gust drives them and the trees.
const leafMesh=new T.InstancedMesh(new T.PlaneGeometry(.075,.19),new T.MeshLambertMaterial({color:'#d2c58c',side:T.DoubleSide,transparent:true,opacity:.72}),36);leafMesh.instanceMatrix.setUsage(T.DynamicDrawUsage);scene.add(leafMesh);const leafDummy=new T.Object3D();
const birds=[];for(let i=0;i<5;i++){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([-1,0,0,0,0,.2,1,0,0],3));const bird=new T.Line(g,new T.LineBasicMaterial({color:'#687f7d'}));scene.add(bird);birds.push(bird);}
function showToast(text,duration=4){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=elapsed+duration;}
function updateMute(){const enabled=sound.enabled;$('mute').setAttribute('aria-pressed',String(enabled));$('mute').setAttribute('aria-label',enabled?'音をオフにする':'音をオンにする');$('mute').querySelector('path').setAttribute('d',enabled?'M11 5 6 9H3v6h3l5 4zM15 8c3 2 3 6 0 8M18 5c5 4 5 10 0 14':'M11 5 6 9H3v6h3l5 4zM16 9l5 6m0-6-5 6');}
function resetInput(){keys.clear();joyX=0;joyY=0;joyId=null;lookId=null;$('stick').style.transform='translate(0,0)';velocity.set(0,0,0);}
function resetPosition(){player.set(0,height(0,16),16);dog.dog.position.set(sideOffset,height(sideOffset,13.2)+.07,13.2);yaw=0;pitch=-.17;petUntil=0;resetInput();}
function pet(){if(!started||paused)return;petUntil=elapsed+3.8;velocity.set(0,0,0);showToast('よしよし。',3.5);}
function openMenu(){resetInput();paused=true;sound.suspend();$('menu').showModal();}
function closeMenu(){paused=false;$('menu').close();if(started)sound.resume();last=performance.now();}
$('settings').onclick=openMenu;$('resume').onclick=closeMenu;$('menu').addEventListener('cancel',()=>{paused=false;last=performance.now();if(started)sound.resume();});$('reset').onclick=()=>{resetPosition();closeMenu();};$('pet').onclick=pet;
$('wind').oninput=e=>windSetting=+e.target.value;$('volume').oninput=e=>sound.setVolume(+e.target.value);$('bob').onchange=e=>bob=e.target.checked;$('quality').onchange=e=>{quality=e.target.value;resolvedQuality=quality!=='auto';renderer.setPixelRatio(quality==='low'?1:quality==='high'?Math.min(devicePixelRatio,2):Math.min(devicePixelRatio,touch?1.35:1.75));renderer.setSize(innerWidth,innerHeight);};
$('mute').onclick=async()=>{if(!sound.ctx){try{const ok=await sound.init();if(!ok)showToast('このブラウザでは音を再生できません。');}catch{showToast('音を再生できませんでした。もう一度お試しください。');}}else{sound.setEnabled(!sound.enabled);if(sound.enabled&&!paused)sound.resume();}updateMute();};
$('begin').onclick=async()=>{started=true;document.body.classList.add('playing');try{const ok=await sound.init();if(!ok)showToast('音なしで散歩を始めます。');}catch{showToast('音なしで散歩を始めます。右上から再試行できます。');}updateMute();showToast('海のほうへ、行ってみよう。',5);};
const joystick=$('joystick');function updateJoystick(e){const r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.34,len=Math.hypot(dx,dy),k=len>max?max/len:1;joyX=dx*k/max;joyY=-dy*k/max;$('stick').style.transform=`translate(${dx*k}px,${dy*k}px)`;}
joystick.addEventListener('pointerdown',e=>{if(paused)return;joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);updateJoystick(e);e.preventDefault();});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joyId)updateJoystick(e);});function endJoystick(e){if(e.pointerId!==joyId)return;joyId=null;joyX=joyY=0;$('stick').style.transform='translate(0,0)';}joystick.addEventListener('pointerup',endJoystick);joystick.addEventListener('pointercancel',endJoystick);joystick.addEventListener('lostpointercapture',endJoystick);
const view=$('view');view.addEventListener('pointerdown',e=>{if(!started||paused||lookId!==null)return;lookId=e.pointerId;lookX=e.clientX;lookY=e.clientY;view.setPointerCapture(e.pointerId);});view.addEventListener('pointermove',e=>{if(e.pointerId!==lookId||paused)return;yaw-=(e.clientX-lookX)*.004;pitch=T.MathUtils.clamp(pitch-(e.clientY-lookY)*.003,-.85,.42);lookX=e.clientX;lookY=e.clientY;});function endLook(e){if(e.pointerId===lookId)lookId=null;}view.addEventListener('pointerup',endLook);view.addEventListener('pointercancel',endLook);view.addEventListener('lostpointercapture',endLook);
addEventListener('keydown',e=>{if(e.code==='Escape'&&started&&!$('menu').open){openMenu();return;}if(!started||paused)return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){keys.add(e.code);e.preventDefault();}if(e.code==='KeyE'&&!e.repeat)pet();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{resetInput();sound.suspend();});addEventListener('focus',()=>{if(started&&!paused)sound.resume();});document.addEventListener('visibilitychange',()=>{resetInput();last=performance.now();if(document.hidden)sound.suspend();else if(started&&!paused)sound.resume();});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
if(!touch)$('controlInfo').textContent='WASD / 矢印キーで歩く　·　ドラッグで見回す　·　Eでなでる';
const zones=[{x:61,z:40,r:16,label:'海の見える公園',text:'葉っぱの音が、近くなる。'},{x:30,z:-30,r:36,label:'海沿いの道',text:'坂の下には、今日も海がある。'},{x:-37,z:48,r:19,label:'グラシアスのある通り',text:'どこかの家から、夕飯の匂い。'},{x:15,z:74,r:25,label:'ヤマグチベーカリーの坂',text:'パン屋の角を、風が曲がっていく。'}];
let dogAngle=0,stoppedFor=0,petBlend=0;
function animate(now){const dt=Math.min(.045,last?(now-last)/1000:.016);last=now;if(document.hidden||paused)return;elapsed+=dt;const t=elapsed,gust=windSetting*(.60+.22*Math.sin(t*.31)+.13*Math.sin(t*.87)+.05*Math.sin(t*1.7));
 forward.set(-Math.sin(yaw),0,-Math.cos(yaw));right.set(Math.cos(yaw),0,-Math.sin(yaw));
 const isPet=t<petUntil;let iy=joyY+(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0),ix=joyX+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);const norm=Math.max(1,Math.hypot(ix,iy));ix/=norm;iy/=norm;const moving=started&&!isPet;
 const targetV=goal.copy(forward).multiplyScalar(moving?iy*2.7:0).addScaledVector(right,moving?ix*2.35:0);velocity.lerp(targetV,1-Math.exp(-dt*8));let nx=player.x+velocity.x*dt,nz=player.z+velocity.z*dt;if(canWalk(nx,nz)){player.x=nx;player.z=nz;}else{if(canWalk(nx,player.z))player.x=nx;if(canWalk(player.x,nz))player.z=nz;velocity.multiplyScalar(.4);}player.y=height(player.x,player.z);const speed=velocity.length();stoppedFor=speed<.1?stoppedFor+dt:0;walkPhase+=speed*dt*2;
 const sniff=!isPet&&stoppedFor>2&&Math.sin(t*.3)>.05;
 if(isPet){goal.copy(player).addScaledVector(forward,1.5).addScaledVector(right,touch?.08:.20);}else if(speed>.1){goal.copy(player).addScaledVector(forward,2.6).addScaledVector(right,sideOffset+Math.sin(t*.32)*.12);}else{goal.copy(player).addScaledVector(forward,2.5).addScaledVector(right,sideOffset+(sniff?Math.sin(t*.45)*.18:0));}
 const dc=constrainDog(goal.x,goal.z);goal.set(dc.x,height(dc.x,dc.z)+.075,dc.z);const delta=v.copy(goal).sub(dog.dog.position),distance=delta.length(),dogSpeed=Math.min(3.8,distance*3.0);if(distance>.035)dog.dog.position.addScaledVector(delta,Math.min(1,dt*dogSpeed/distance));dog.dog.position.y=height(dog.dog.position.x,dog.dog.position.z)+.075;
 let targetAngle=dogAngle;if(isPet)targetAngle=Math.atan2(dog.dog.position.x-player.x,dog.dog.position.z-player.z);else if(distance>.12)targetAngle=Math.atan2(-delta.x,-delta.z);dogAngle+=Math.atan2(Math.sin(targetAngle-dogAngle),Math.cos(targetAngle-dogAngle))*Math.min(1,dt*6);dog.dog.rotation.y=dogAngle;dog.animate(t,dogSpeed,isPet,sniff);
 petBlend=T.MathUtils.lerp(petBlend,isPet?1:0,1-Math.exp(-dt*3));
 camera.position.copy(player);camera.position.y+=1.68-petBlend*.18+(bob?Math.sin(walkPhase*2)*Math.min(speed,1)*.025:0);camera.rotation.set(T.MathUtils.lerp(pitch,-.38,petBlend*.65),yaw,0,'YXZ');camera.updateMatrixWorld();hand.set(.25,-.47,-.4).applyMatrix4(camera.matrixWorld);collar.set(0,.79,-.29).applyMatrix4(dog.dog.matrixWorld);dog.dog.updateMatrixWorld(true);collar.set(0,.79,-.29).applyMatrix4(dog.dog.matrixWorld);mid.copy(hand).lerp(collar,.5);mid.y-=Math.max(.15,.65-hand.distanceTo(collar)*.09);for(let i=0;i<25;i++){const u=i/24,inv=1-u;leashPos[i*3]=inv*inv*hand.x+2*inv*u*mid.x+u*u*collar.x;leashPos[i*3+1]=inv*inv*hand.y+2*inv*u*mid.y+u*u*collar.y;leashPos[i*3+2]=inv*inv*hand.z+2*inv*u*mid.z+u*u*collar.z;}leashGeo.attributes.position.needsUpdate=true;
 clouds.forEach((c,i)=>c.position.x=-250+i*85+Math.sin(t*.015+i)*12);
 world.update(t,gust);water.material.uniforms.time.value=t;water.material.uniforms.breeze.value=gust;
 for(let i=0;i<36;i++){const phase=i*1.731,x=player.x+((i*2.137+t*(.65+gust*1.8))%25)-12.5,z=player.z+((i*3.731+t*.2)%24)-12,y=height(x,z)+.4+((i*.63+t*.16)%4);leafDummy.position.set(x,y,z);leafDummy.rotation.set(t+i,phase+t*.8,t*.6);const visible=windSetting>.08&&i<8+windSetting*28;leafDummy.scale.setScalar(visible?.7+gust*.5:0);leafDummy.updateMatrix();leafMesh.setMatrixAt(i,leafDummy.matrix);}leafMesh.instanceMatrix.needsUpdate=true;
 birds.forEach((b,i)=>{b.position.set(Math.sin(t*.035+i)*90,25+i*3,-110+Math.cos(t*.035+i)*20);b.rotation.y=-t*.035-i;const a=b.geometry.attributes.position;a.setY(0,Math.sin(t*3+i)*.32);a.setY(2,Math.sin(t*3+i)*.32);a.needsUpdate=true;});
 const park=Math.hypot(player.x-61,player.z-40)<16;if(started){sound.update(t,gust,player.z,yaw,speed,park);const zone=zones.find(z=>Math.hypot(player.x-z.x,player.z-z.z)<z.r),name=zone?.label||'海へ向かう坂道';if(name!==lastPlace){$('place').textContent=name;if(lastPlace&&zone&&t-lastZoneTime>15){showToast(zone.text,4);lastZoneTime=t;}lastPlace=name;}}
 if(t>toastUntil)$('toast').classList.remove('show');renderer.render(scene,camera);
 if(started&&quality==='auto'&&!resolvedQuality){frameCount++;frameTotal+=dt;if(frameCount===160){if(frameTotal/frameCount>.028){renderer.setPixelRatio(1);renderer.setSize(innerWidth,innerHeight);}resolvedQuality=true;}}
}
renderer.setAnimationLoop(animate);$('begin').disabled=false;$('loading').textContent='散歩に出かける';
